spring:
  application:
    name: project-management
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgress
    password:     
    driver-class-name: org.postgresql.Driver  
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none  
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
    host: localhost
    port: 8000